sudo: required

language: php
php:
  - '7.1'

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

before_install:
  # Update Docker
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  # Update Docker-Compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - composer install
  - docker-compose up --build -d
