version: '3'
services:
  simple:
    build: .
    image: simple
    depends_on:
      - mysql
    ports:
      - "8888:80"
    environment:
      - DB_NAME=simple
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
    restart: unless-stopped
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql-volume: